---
title: Mörk Chocolate UK
timezone: UTC
collections:
  chocolates:
    title: Chocolates
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
typekit: wwu7klm
analytics: UA-34047801-
