---
title: Mörk Chocolate
timezone: Melbourne
collections:
  chocolates:
    title: Chocolates
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
url: http://mork.siteleaf.net
permalink: pretty
typekit: wwu7klm
analytics: UA-34047801-1
markdown: redcarpet
redcarpet:
  extensions:
  - autolink
  - fenced_code_blocks
  - lax_spacing
  - strikethrough
  - superscript
  - tables
  - footnotes
  - highlight
